---

- block:
    - name: 'Debian/Ubuntu | Install apt-transport-https and ca-certificates'
      apt:
        cache_valid_time: 3600
        name:
          - 'apt-transport-https'
          - 'ca-certificates'
        state: 'present'
      async: '{{ wazuh_async_timeout }}'
      poll: '{{ wazuh_async_poll }}'
      when: 'wazuh_repo_add or nodejs_repo_add'
    - block:
        - name: 'Debian/Ubuntu | Installing Wazuh repository key'
          apt_key:
            url: '{{ wazuh_repo_key }}'
          async: '{{ wazuh_async_timeout }}'
          poll: '{{ wazuh_async_poll }}'
        - name: 'Debian/Ubuntu | Add Wazuh repositories'
          apt_repository:
            repo: '{{ wazuh_repo }}'
            state: 'present'
            update_cache: true
          async: '{{ wazuh_async_timeout }}'
          poll: '{{ wazuh_async_poll }}'
      when: 'wazuh_repo_add'
    - block:
        - name: 'Debian/Ubuntu | Installing NodeJS repository key (apt_key)'
          apt_key:
            url: '{{ nodejs_repo_key }}'
          async: '{{ wazuh_async_timeout }}'
          poll: '{{ wazuh_async_poll }}'
        - name: 'Debian/Ubuntu | Add NodeSource repositories for Node.js'
          apt_repository:
            repo: '{{ nodejs_repo }}'
            state: 'present'
            update_cache: true
          async: '{{ wazuh_async_timeout }}'
          poll: '{{ wazuh_async_poll }}'
      when: 'nodejs_repo_add'

- block:
    - name: 'Debian/Ubuntu | Setting java repository'
      apt_repository:
        repo: '{{ java_repo }}'
        codename: '{{ java_repo_release }}'
        update_cache: true
      async: '{{ wazuh_async_timeout }}'
      poll: '{{ wazuh_async_poll }}'
      tags:
        - 'init'
      when: 'java_repo_add'
    - name: 'Debian/Ubuntu | Accept Oracle Java 8 license'
      debconf:
        name: 'oracle-java8-installer'
        question: 'shared/accepted-oracle-license-v1-1'
        value: true
        vtype: 'boolean'
      tags:
        - 'init'
    - name: 'Debian/Ubuntu | Oracle Java 8 installer'
      apt:
        name: 'oracle-java8-installer'
        state: 'present'
        cache_valid_time: 3600
      async: '{{ wazuh_async_timeout }}'
      poll: '{{ wazuh_async_poll }}'
      tags:
        - 'init'
  when:
    - 'wazuh_ciscat_enabled|default(false)'
    - 'wazuh_java_install'

- block:
    - name: 'Debian/Ubuntu | Install OpenScap'
      package:
        name:
          - 'libopenscap8'
          - 'xsltproc'
        state: 'present'
        cache_valid_time: 3600
      async: '{{ wazuh_async_timeout }}'
      poll: '{{ wazuh_async_poll }}'
      tags:
        - 'init'
    - name: 'Debian/Ubuntu | Get OpenScap installed version'
      changed_when: true
      register: 'openscap_version'
      shell: "dpkg-query --showformat='${Version}' --show libopenscap8"
      tags:
        - 'config'
    - name: 'Debian/Ubuntu | Check OpenScap version'
      changed_when: true
      register: 'openscap_version_valid'
      shell: 'dpkg --compare-versions "{{ openscap_version.stdout }}"
              ">=" "1.2"; echo $?'
      tags:
        - 'config'
  when: 'wazuh_openscap_enabled|default(false)'
