---

- name: 'RedHat/CentOS/Fedora |
         Remove NodeJS repository (and clean up left-over metadata)'
  yum_repository:
    name: 'NodeJS'
    state: 'absent'
  when: 'wazuh_repo_add and wazuh_repo_remove'

- name: 'RedHat/CentOS/Fedora |
         Remove Wazuh repository (and clean up left-over metadata)'
  yum_repository:
    name: 'wazuh_repo'
    state: 'absent'
  when: 'nodejs_repo_add and nodejs_repo_remove'
